version: '3'

services:
  tokens:
    build: .
    volumes:
      - .:/app
    environment:
      - SHELL=/bin/bash
    command: "npm run watch-tokens"
  
  svgs:
    build: .
    volumes:
      - .:/app
    environment:
      - SHELL=/bin/bash
    command: "npm run watch-svgs"

  css:
    build: .
    volumes:
      - .:/app
    environment:
      - SHELL=/bin/bash
    command: "npm run watch-css"

  components:
    build: .
    volumes:
      - .:/app
    command: "npm run watch-components"

  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: "npm start"
