/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MChat {}
  interface MUniversalHeader {}
}

declare global {


  interface HTMLMChatElement extends Components.MChat, HTMLStencilElement {}
  var HTMLMChatElement: {
    prototype: HTMLMChatElement;
    new (): HTMLMChatElement;
  };

  interface HTMLMUniversalHeaderElement extends Components.MUniversalHeader, HTMLStencilElement {}
  var HTMLMUniversalHeaderElement: {
    prototype: HTMLMUniversalHeaderElement;
    new (): HTMLMUniversalHeaderElement;
  };
  interface HTMLElementTagNameMap {
    'm-chat': HTMLMChatElement;
    'm-universal-header': HTMLMUniversalHeaderElement;
  }
}

declare namespace LocalJSX {
  interface MChat {}
  interface MUniversalHeader {}

  interface IntrinsicElements {
    'm-chat': MChat;
    'm-universal-header': MUniversalHeader;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'm-chat': LocalJSX.MChat & JSXBase.HTMLAttributes<HTMLMChatElement>;
      'm-universal-header': LocalJSX.MUniversalHeader & JSXBase.HTMLAttributes<HTMLMUniversalHeaderElement>;
    }
  }
}


