/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MCallout {
        "dismissable": boolean;
        "icon": boolean;
        "subtle": boolean;
        "variant": 'info' | 'success' | 'error' | 'warning';
    }
    interface MChat {
    }
    interface MIcon {
        "name": string;
        "size": string;
    }
    interface MLogo {
        /**
          * Select the Website Header variant.  Options:   - light   - dark
         */
        "variant": string;
    }
    interface MUniversalHeader {
    }
    interface MWebsiteAlerts {
    }
    interface MWebsiteHeader {
        /**
          * The user-friendly name of the U-M Library website that uses this Header.
         */
        "name": string;
        /**
          * The URL linked to when you click the website name.
         */
        "to": string;
        /**
          * Optionally set to `dark` for a blue background.
         */
        "variant": string;
    }
}
declare global {
    interface HTMLMCalloutElement extends Components.MCallout, HTMLStencilElement {
    }
    var HTMLMCalloutElement: {
        prototype: HTMLMCalloutElement;
        new (): HTMLMCalloutElement;
    };
    interface HTMLMChatElement extends Components.MChat, HTMLStencilElement {
    }
    var HTMLMChatElement: {
        prototype: HTMLMChatElement;
        new (): HTMLMChatElement;
    };
    interface HTMLMIconElement extends Components.MIcon, HTMLStencilElement {
    }
    var HTMLMIconElement: {
        prototype: HTMLMIconElement;
        new (): HTMLMIconElement;
    };
    interface HTMLMLogoElement extends Components.MLogo, HTMLStencilElement {
    }
    var HTMLMLogoElement: {
        prototype: HTMLMLogoElement;
        new (): HTMLMLogoElement;
    };
    interface HTMLMUniversalHeaderElement extends Components.MUniversalHeader, HTMLStencilElement {
    }
    var HTMLMUniversalHeaderElement: {
        prototype: HTMLMUniversalHeaderElement;
        new (): HTMLMUniversalHeaderElement;
    };
    interface HTMLMWebsiteAlertsElement extends Components.MWebsiteAlerts, HTMLStencilElement {
    }
    var HTMLMWebsiteAlertsElement: {
        prototype: HTMLMWebsiteAlertsElement;
        new (): HTMLMWebsiteAlertsElement;
    };
    interface HTMLMWebsiteHeaderElement extends Components.MWebsiteHeader, HTMLStencilElement {
    }
    var HTMLMWebsiteHeaderElement: {
        prototype: HTMLMWebsiteHeaderElement;
        new (): HTMLMWebsiteHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "m-callout": HTMLMCalloutElement;
        "m-chat": HTMLMChatElement;
        "m-icon": HTMLMIconElement;
        "m-logo": HTMLMLogoElement;
        "m-universal-header": HTMLMUniversalHeaderElement;
        "m-website-alerts": HTMLMWebsiteAlertsElement;
        "m-website-header": HTMLMWebsiteHeaderElement;
    }
}
declare namespace LocalJSX {
    interface MCallout {
        "dismissable"?: boolean;
        "icon"?: boolean;
        "subtle"?: boolean;
        "variant"?: 'info' | 'success' | 'error' | 'warning';
    }
    interface MChat {
    }
    interface MIcon {
        "name"?: string;
        "size"?: string;
    }
    interface MLogo {
        /**
          * Select the Website Header variant.  Options:   - light   - dark
         */
        "variant"?: string;
    }
    interface MUniversalHeader {
    }
    interface MWebsiteAlerts {
    }
    interface MWebsiteHeader {
        /**
          * The user-friendly name of the U-M Library website that uses this Header.
         */
        "name"?: string;
        /**
          * The URL linked to when you click the website name.
         */
        "to"?: string;
        /**
          * Optionally set to `dark` for a blue background.
         */
        "variant"?: string;
    }
    interface IntrinsicElements {
        "m-callout": MCallout;
        "m-chat": MChat;
        "m-icon": MIcon;
        "m-logo": MLogo;
        "m-universal-header": MUniversalHeader;
        "m-website-alerts": MWebsiteAlerts;
        "m-website-header": MWebsiteHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "m-callout": LocalJSX.MCallout & JSXBase.HTMLAttributes<HTMLMCalloutElement>;
            "m-chat": LocalJSX.MChat & JSXBase.HTMLAttributes<HTMLMChatElement>;
            "m-icon": LocalJSX.MIcon & JSXBase.HTMLAttributes<HTMLMIconElement>;
            "m-logo": LocalJSX.MLogo & JSXBase.HTMLAttributes<HTMLMLogoElement>;
            "m-universal-header": LocalJSX.MUniversalHeader & JSXBase.HTMLAttributes<HTMLMUniversalHeaderElement>;
            "m-website-alerts": LocalJSX.MWebsiteAlerts & JSXBase.HTMLAttributes<HTMLMWebsiteAlertsElement>;
            "m-website-header": LocalJSX.MWebsiteHeader & JSXBase.HTMLAttributes<HTMLMWebsiteHeaderElement>;
        }
    }
}
