name: Build and Publish Pull Request
on: 
  push:

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  npm_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: config git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: install dependencies
        run: npm install
      - name: build package
        run: npm run build
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: bump up version
        run: |
          npm version prerelease --no-git-tag-version --preid ${{ steps.extract_branch.outputs.branch }} 
          git commit -am "update prerelease version"
          git push
      - name: publish
        run: npm publish --access public
