name: Set @latest on given version
on: 
  workflow_dispatch:
    inputs:
      version:
        description: version 
        required: true

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  npm_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: tag version
        run: npm dist-tag add @umich-lib/web@${{ github.event.inputs.version }} latest
